services:
  app:
    build:
      dockerfile: Dockerfile
    working_dir: /app
    command: make dev
    environment:
      DATABASE_URL: ${DATABASE_URL}
      MIGRATIONS_DIR: ${MIGRATIONS_DIR}
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - .:/app
  db:
    image: postgres:latest
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: quotes
    ports:
      - "5432:5432"
    volumes:
      - .pgdata:/var/lib/postgresql/data
