// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go
//
// Generated by this command:
//
//	mockgen -package=repositorytest -source=repository.go -destination=repositorytest/repository.go .
//

// Package repositorytest is a generated GoMock package.
package repositorytest

import (
	context "context"
	reflect "reflect"

	repository "github.com/GoCodingX/gorilla/internal/repository"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CreateQuote mocks base method.
func (m *MockRepository) CreateQuote(ctx context.Context, quote *repository.Quote) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateQuote", ctx, quote)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateQuote indicates an expected call of CreateQuote.
func (mr *MockRepositoryMockRecorder) CreateQuote(ctx, quote any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateQuote", reflect.TypeOf((*MockRepository)(nil).CreateQuote), ctx, quote)
}
